feature/hosts
csnewman/libnss-rs pull request #1
Opened 2019-06-15 05:15 UTC by ryankurte

hey thanks for making a neat (and well timed) thing!

this PR adds hosts module with hooks and macros, definitely needs a review for correctness.

2019-06-19 19:03 UTC, csnewman requested changes

2019-06-19 19:03 UTC, csnewman commented on libnss/src/host.rs
> +
Formatting

2019-06-19 19:03 UTC, csnewman commented on libnss/src/host.rs
> +
Formatting

2019-06-19 19:03 UTC, csnewman commented on libnss/src/host.rs
> +                    array_pos = array_pos.offset(1);
Seems quite spaced out

2019-06-19 19:03 UTC, csnewman commented on libnss/src/host.rs
> +
Formatting

2019-06-19 19:04 UTC, csnewman commented
Generally great, just some minor style choices.

2019-06-26 10:43 UTC, ryankurte commented
i gave it a `cargo fmt` pass and removed a little bit of whitespace, but, i'm not sure what your other formatting comments refer to..? 

(also i only applied the new formatting to this file to avoid burying the PR in noise, you might consider running it against the whole repo too)

2019-06-29 17:08 UTC, csnewman requested changes

2019-06-29 17:08 UTC, csnewman commented on libnss/src/host.rs
> +
Should only be one new whiteline here

2019-06-29 17:08 UTC, csnewman commented on libnss/src/host.rs
> +
No need for 3 whitelines

2019-07-02 18:29 UTC, merged

2019-07-02 18:29 UTC, csnewman commented
Thanks

2019-09-15 01:32 UTC, bjeanes commented on libnss/src/host.rs
> +        let (addr_len, count) = match &self.addresses {
If I am understanding this correctly, this makes it possible to only return a list of V4 addresses OR a list of V6 addresses, but not possible to return a list of all V4 AND V6 addresses for a host.

Assuming my interpretation is correct, is this an inherit limitation of the NSS C API or just of this shim?

2019-09-15 06:41 UTC, bjeanes commented on libnss/src/host.rs
> +        let (addr_len, count) = match &self.addresses {
I read the https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_chapter/libc_16.html#SEC318 link in these docs and it does appear to be inherent in the shape of the struct we need to return. Bummer.

2019-09-15 06:56 UTC, bjeanes commented
I might have made an error that I've missed, but `get_host_by_name` does not appear to be called. I have added logger statements to the three functions and when using `getent hosts` I see that `get_all_entries` is called. `getent hosts 1.2.3.4` shows that `get_host_by_addr` is called, but `getent hosts foo.bar` indicates that `get_host_by_name` is NOT called.

Furthermore, if I return `None` (or `vec![]` for `get_all_entries`) all is fine, but if I actually return a `Host`, I get a segmentation fault! I think the host struct may not be getting laid out correctly?

2019-09-15 08:38 UTC, bjeanes commented
> `getent hosts foo.bar` indicates that `get_host_by_name` is NOT called.

On my system, at least, the function is expected to be called the equivalent of `[<_nss_ $mod_ident _gethostbyname2_r>]` (note the trailing `2`).

I have looked at some other source and mailing lists and it seems like this is all a mess. At the very least, having the non-`2` version just call the first one seems like a viable patch. I'll get a bit further with my changes and then open a PR that brings it closer to what seems to be done in practice: https://github.com/lathiat/nss-mdns/blob/58fcdd2071eb64372f071cee14982536fd4c7a99/src/nss.c#L215-L262

See also https://libc-alpha.sourceware.narkive.com/Bouz4PWh/patch-bz-16077-get-canonical-name-in-getaddrinfo-from-hosts-file-for-af-inet

2019-09-15 08:39 UTC, bjeanes commented
> if I actually return a `Host`, I get a segmentation fault!

I am still not sure about these, so I am going to go over the `CHost` construction carefully and see if I can spot anything obvious...

2019-09-16 02:19 UTC, bjeanes commented on libnss/src/host.rs
> +    pub h_aliases: *mut libc::c_char,
I think this should be:

``` suggestion
    pub h_aliases: *mut *mut libc::c_char,
```

I think this is the cause of my segfaults. https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_chapter/libc_16.html#SEC318 defines its type as `char **h_aliases`. Changing it in my local copy fixes the segfault but I must have a different error with my pointer fiddling as `getent` prints out the first alias but then gibberish for the second one (but doesn't segfault!).